# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/aarunvignesh/myblogger" }

gem "require_all"
gem "sinatra"
gem "bundler"
gem "webrick"
gem "shotgun"
gem "sinatra-contrib"
gem "faraday"
gem "rake"
gem "slim", "~> 4.0"

group :test do
  gem "minitest"
  gem "rack-test"
end